### ISSUE TITLE
rh-ruby26: define GEM_HOME in enable script

### ISSUE THREAD

**Issue by VVD** [iusrepo/packaging#10]
1. Didn't find subproject for ruby - please move this issue to correct place or just show it and I'll copy&paste it self.
2. Requested add to file /opt/rh/rh-ruby26/enable line:
```
export GEM_HOME=/opt/rh/rh-ruby26/root/usr/local/share/gems
```
3. Detailed description "why I suggest this" is here: https://github.com/rubygems/rubygems/issues/3881

Thanks!

**Comment by carlwgeorge** [comment]
IUS doesn't currently package ruby.  That appears to be a software collection, which we don't do either.

**Comment by VVD** [comment]
What?
I installed it 3 months ago from this repo: https://repo.ius.io/7.
Is it your repo or I'm wrong and it's different repo?

**Comment by VVD** [comment]
Hm.
I think I really mix up the repository.
Sorry. :-(

**Comment by VVD** [comment]
I'm using git from your repository only - "my bad".
