### ISSUE TITLE
Discussion: Adding documentation for package updates?

### ISSUE THREAD

**Issue by ghost** [iusrepo/packaging#5]
What are the thoughts on adding how a new contributor should go about updating existing packages?

In many cases it may be as simple as a version bump, but in others patches may need to be pulled from the Fedora packages and added for IUS. In the latter case it isn't clear which patches may or may not be needed (likely this comes with experience but documenting for new contributors couldn't hurt), and there are associated changelog entries which maybe should be brought over too for the history to be maintained.

**Comment by carlwgeorge** [comment]
Thanks for the suggestion.  I agree, a guide with general instructions would be useful.  Every patch will be a case by case basis if it's worthwhile to merge back to the IUS package.  For example, a patch to fix a compilation issue with the latest OpenSSL wouldn't apply to IUS.  A patch fixing a CVE that isn't in a tagged upstream version yet would be useful.  Examples like these would be the bulk of such a guide.

As a general rule, the goal is the keep the IUS package updated to the latest upstream version, not to keep it in sync with Fedora.  Other than rebasing patches or removing patches that have been merged upstream (both necessary to get the package to build), any new patches should be appropriately justified in the pull request.  If the contributor can't articulate why the patch should be merged from Fedora, then it probably isn't a good fit.

Another common occurrence is Fedora changing their subpackage layout.  This makes sense with Fedora's six month release cycle, as these changes can be introduced in Rawhide with minimal disruption and be given time to bake.  These types of changes have to potential to be disruptive for IUS users, and would need a strong justification and careful testing of provides/obsoletes to ensure a clean upgrade path.

These are just some of my initial thoughts on the matter, if you want to elaborate on them and start writing up a guide that would be awesome.

**Comment by carlwgeorge** [comment]
The IUS project has reached it's end of life, and will not be addressing any more issues or pull requests.

ius.io/faq#why-doesnt-ius-have-packages-for-rhel-8

iusrepo/announce#41
