### ISSUE TITLE
Plans for RHEL 8

### ISSUE THREAD

**Issue by crankedguy** [iusrepo/packaging#6]
Hi,

are there any plans in the near future to provide repos/packages for RHEL 8?

Would be an important information as I use ius quite heavily in production.

Thanks

**Comment by carlwgeorge** [comment]
What is missing from RHEL 8 that you would like IUS to provide?  [Application Streams (modularity)](https://developers.redhat.com/blog/2018/11/15/rhel8-introducing-appstreams/) are a holistic replacement for both IUS and Software Collections.  They are designed to allow Red Hat to deliver opt-in newer versions of software later in the RHEL 8 lifecycle.  RHEL 8 already has:

* httpd 2.4.37
* mariadb 10.3.11
* mysql 8.0.13
* php 7.2.11 (7.3 is [coming soon](https://bugzilla.redhat.com/show_bug.cgi?id=1653109))
* nginx 1.14.1
* nodejs 10.14.1
* python 3.6.8
* redis 5.0.3
* ruby 2.5.3
* varnish 6.0.2

I'm not ruling out IUS for RHEL 8 but at this point I just don't know what it would even provide.

**Comment by crankedguy** [comment]
Thanks for getting back to me on that!

Yes I know about the concept of the Application Streams but at the time of writing they are already back half a years compared to some IUS releases. And the big question is when does RedHat release newer versions - or better how do they make use of the possibility to release on a more frequent basis? 
The concept they had does not work out for the needs nowadays, hence AppStream... That's ok but 6 months back can also be a long time.
E.g I am waiting hardly for a fix in MariaDB that is not directly a security fix (which RH provides/provided normally). This is OK as I am using the direct repo provided by MariaDB. I am - or was - using "provider repos" wherever possible (MariaDB, Dovecot, Ghettoforge for postfix) to be up to date. 

From IUS it was always great to have pretty much the latest Apache and PHP versions.

I don't want to leave RHEL/CentOS for a distro that is more bleeding edge in total as I love the stable core they have yet I want to be on "latest" for some applications I run and I cannot yet see this happening with AppStream.

That's why I was asking.

**Comment by carlwgeorge** [comment]
The intent of appstreams is to be able to update to the latest version of an upstream branch.  Red Hat QA does take a little bit of time.  If a stream is 6 months behind, and that presents an actual problem for you, open a support case with Red Hat to nudge them.

I'm not expecting this to be as big a problem as you think.  Red Hat used to be really bad about freezing versions and only backporting, but EL8 will be different.  You can even see that behavior in some EL7 packages.  mariadb in EL7 was updated in almost every point release, from 5.5.35 all the way through 5.5.60.

A six month delay for Red Hat packages doesn't justify the effort required to create IUS packages, much less keep maintaining them for the entire upstream lifecycle after the appstream equivalent is released.  Additionally, EPEL plans on offering appstream as well, so streams can be short lived there before becoming official from Red Hat.

If I'm wrong, and Red Hat lets us down, we can of course revisit this.  But as it stands now, IUS for EL8 doesn't seem likely.
