### ISSUE TITLE
Python 3 plan

### ISSUE THREAD

**Issue by carlwgeorge** [iusrepo/packaging#7]
The Python 3 package ecosystem for EL6 and EL7 has gotten a bit confusing.  There is duplication between IUS and EPEL, and [python3 was just added to RHEL 7.7][rhel-7.7].

EL6:

|      | 3.4       | 3.5       | 3.6       |
| ---- | --------- | --------- | --------- |
| base |           |           |           |
| EPEL | python34  |           |           |
| IUS  | python34u | python35u | python36u |

EL7:

|      | 3.4       | 3.5       | 3.6       |
| ---- | --------- | --------- | --------- |
| base |           |           | python3   |
| EPEL | python34  |           | python36  |
| IUS  | python34u | python35u | python36u |

To reduce confusion and duplicate/unnecessary work, I want to consolidate these packages in a few ways.

# Sync with EPEL

I have already been collaborating with the Fedora Python SIG to maintain the EPEL packages.  The IUS and EPEL packages are very similar.  I'm working on syncing the IUS packages to their EPEL equivalent so that they are effectively the same.  This will include renaming the IUS packages to remove the "u" suffix.  python35u doesn't have an EPEL equivalent, but will also be renamed to drop the "u" for consistency.

# Upgrade path

Renaming these packages will provide a clean upgrade path to switch users to either the stock RHEL python3 package or to an EPEL package.

## python34

* EL6 upgrade path
  - python34u-3.4.8-1.el7 from IUS (current)
  - python34-3.4.8-2.el7 from IUS, obsoletes python34u
  - python34-3.4.10-1.el6 from EPEL
* EL7 upgrade path
  - python34u-3.4.8-1.el7 from IUS (current)
  - python34-3.4.8-2.el7 from IUS, obsoletes python34u
  - python34-3.4.10-2.el6 from EPEL

Technically 3.4 is already EOL upstream, so it could be removed outright from IUS.  However, the Fedora Python SIG plans to keep python34 available in EPEL and do best-effort security backports.  The best outcome would be to switch users to that.

## python35

Business as usual here, as only IUS provides this version.  It will be renamed to drop the "u" for consistency.

## python36

* EL6 upgrade path
  - python36u-3.6.8-1.el7 from IUS (current)
  - python36-3.6.8-2.el7 from IUS, obsoletes python36u
* EL7 upgrade path
  - python36u-3.6.8-1.el7 from IUS (current)
  - python36-3.6.8-2.el7 from IUS, obsoletes python36u
  - python3-3.6.8-10.el7 from base, obsoletes python36

EPEL doesn't have python36 for EL6, so it will be continued to be maintained in IUS for EL6.  With python3 being added to RHEL 7.7, users need to switch to that, and I aim to provide the packages for that upgrade path.  The key thing that enables this is the RHEL python3 package obsoletes the python36 name from EPEL.  This is the primary motivation to rename the IUS package to drop the "u" suffix, so we can get caught in that obsolete condition.

# Future Python versions

I know there is demand to get python37 and eventually other newer versions as they are released upstream.  Since these parallel packages are eligible to be added to EPEL, I'm not interested in maintaining them in IUS.  Once the work outlined above is complete, I'm going to shift my focus to adding python37 to EPEL.  It will take some effort to sort out how the EPEL macros should work, and must take into consideration how existing EPEL python3 add on packages work.

[rhel-7.7]: https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/7.7_release_notes/new_features#enhancement_compiler-and-tools

**Comment by carlwgeorge** [comment]
python36-3.6.8-2 has been published to the testing repo for both EL6 and EL7.  The upgrade paths seem to work as expected.

**Comment by yodermk** [comment]
Thanks Carl. This sounds sane, and should lead to a better Python experience for *EL. Appreciate all you've done in this area so far!

**Comment by carlwgeorge** [comment]
python34-3.4.10-3 has been published to the testing repo for both EL6 and EL7.

One thing to note, as this spec file has been synced with EPEL, is that it now uses the notion of "[main python3](https://github.com/iusrepo/python34/commit/dc61c4f563707b0bccf2b32a357323099d692f92)".  EPEL designates one python3 implementation as the main one via the `python3_pkgversion` macro.

```
root@el6 ~ # rpm -E %python3_pkgversion
34
```
```
root@el7 ~ # rpm -E %python3_pkgversion
36
```

The main python3 package owns `/usr/bin/python3` and other commands that only contain the major version.  In IUS, python34u was the main version everywhere.  For EL6, this doesn't change with this update.  However on EL7, this means that `/usr/bin/python3` moves from python34(u) to python36(u).  [This has been requested](https://github.com/iusrepo/packaging/issues/1) before, but we never addressed it.  It was a rough transition for EPEL when they switched EL7 from 34 to 36 (part of the reason we never did it with IUS), but to move forward with maintaining python3 packages in EPEL, we can't avoid it.

**Comment by carlwgeorge** [comment]
I was hoping to get more testing feedback before pushing these updates to stable, but there is now a dependency resolution issue with the release of RHEL 7.7 and CentOS 7.1908.  Trying to install any of the new python3 modules from base results in a yum transaction that tries to install both python36u and python3, which fails due to file conflicts.  Enabling ius-testing resolves the error.  I'm going to go ahead and push python34 and python36 to stable.

I still need to update python35, and at some point all python34 packages need to be retired since it is EOL upstream.

**Comment by killswitch-GUI** [comment]
@carlwgeorge I don't know if this relevant but I get this now trying to install pyhton36u. I don't believe this was the case this morning. could be my setup tho.

```
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirrors.cat.pdx.edu
 * extras: mirrors.cat.pdx.edu
 * updates: mirrors.cat.pdx.edu
Package python36u is obsoleted by python3, trying to install python3-3.6.8-10.el7.x86_64 instead
Resolving Dependencies
There are unfinished transactions remaining. You might consider running yum-complete-transaction, or "yum-complete-transaction --cleanup-only" and "yum history redo last", first to finish them. If those don't work you'll have to try removing/installing packages by hand (maybe package-cleanup can help).
--> Running transaction check
---> Package python3.x86_64 0:3.6.8-10.el7 will be installed
--> Processing Dependency: python3-libs(x86-64) = 3.6.8-10.el7 for package: python3-3.6.8-10.el7.x86_64
--> Processing Dependency: python3-setuptools for package: python3-3.6.8-10.el7.x86_64
--> Processing Dependency: python3-pip for package: python3-3.6.8-10.el7.x86_64
--> Running transaction check
---> Package python3-libs.x86_64 0:3.6.8-10.el7 will be installed
---> Package python3-pip.noarch 0:9.0.3-5.el7 will be installed
---> Package python3-setuptools.noarch 0:39.2.0-10.el7 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

==============================================================================================================================================================================================================================================
 Package                                                          Arch                                                 Version                                                       Repository                                          Size
==============================================================================================================================================================================================================================================
Installing:
 python3                                                          x86_64                                               3.6.8-10.el7                                                  base                                                69 k
Installing for dependencies:
 python3-libs                                                     x86_64                                               3.6.8-10.el7                                                  base                                               7.0 M
 python3-pip                                                      noarch                                               9.0.3-5.el7                                                   base                                               1.8 M
 python3-setuptools                                               noarch                                               39.2.0-10.el7                                                 base                                               629 k

Transaction Summary
==============================================================================================================================================================================================================================================
Install  1 Package (+3 Dependent packages)

Total size: 9.4 M
Installed size: 48 M
Is this ok [y/d/N]:
```

**Comment by killswitch-GUI** [comment]
Before we used python36u-mod_wsgi to install the properly compiled mod_wsgi. How do we do that now with IUS?

**Comment by rsichnyi** [comment]
so apparently this broke some things...
We have a rpm package which has `Requires: python36u`. the following fails:
```
$ yum install python36u
$ yum install <our-package>
```
the error:
```
Error: Package: <our-package>
  Requires: python36u
  Available: python36-3.6.8-2.el7.ius.x86_64 (ius)
                  python36u = 3.6.8-2.el7.ius
  Available: python36u-3.6.8-1.el7.ius.x86_64 (ius)
                   python36u = 3.6.8-1.el7.ius
  Available: python36-3.6.8-1.el7.x86_64 (epel)
  Not found
```

**Comment by carlwgeorge** [comment]
@rsichny There is nothing I can do about this.  The python36u package is being deprecated in favor of the Red Hat python3 package.  When you ask yum to install python36u, it sees that the python36 package from IUS obsoletes python36u, and then it sees that the python3 package from base obsoletes python36.  The python3 package provides python36, but not python36u.  Short term fix, you can exclude python3 on your system.  Long term, you have a few options in how you fix your package.

- change your requires from python36u to python36.
- change your requires to `/usr/bin/python3`
- change your requires to `python(abi) = 3.6` (this may have already been added automatically by rpmbuild)

**Comment by rsichnyi** [comment]
@carlwgeorge I know how to fix it, and yes, it's not a huge issue, just not sure if making python36u obsolete was a right decision, it had different name for a reason...

**Comment by carlwgeorge** [comment]
@rsichny That was the only way to transition users to the new python3 package from base.  It's pointless for IUS to duplicate the work of maintaining that version of Python if Red Hat is already doing it.

**Comment by carlwgeorge** [comment]
python34-3.4.10-4 in EPEL now obsoletes the python34u name, so users of that package will have a seamless upgrade path once that is published even if they never upgraded to the IUS python34 package.

**Comment by carlwgeorge** [comment]
I'm getting continued reports of the EL7 python36u -> python3 upgrade path not working.  Despite the obsoletes resolution working as expected, after accepting the transaction there are many errors similar to this:

```
file /usr/bin/python3.6 from install of python3-3.6.8-10.el7.x86_64 conflicts with file from package python36u-3.6.8-1.el7.ius.x86_64
```

If you are hitting this issue, you can work around it by breaking the update into two steps.

1. Update from python36u to python36, explicitly excluding python3.

```
yum --exclude python3,python3-\* update python36u\*
```

Note: If you have python36u-devel installed, you'll need to install it's python3-rpm-macros dependency first, to avoid it being excluded.

2. Update from python36 to python3.

```
yum update python36\*
```

Alternatively, if you install dnf from the extras repo (which is generally [useful for IUS](https://ius.io/usage#dnf)), you don't have to think about this.  Dnf will naturally break the update into two stages, and all you have to do is run `dnf update` twice.

**Comment by jx759** [comment]
Hi Carl - thank you for sharing this work around, unfortunately I continued to have issues.

> 
> 1. Update from python36u to python36, explicitly excluding python3.
> 
> ```
> yum --exclude python3,python3-\* update python36u
> ```

Step 1 completed without issue.

> 
> 2. Update from python36 to python3.
> 
> ```
> yum update python36
> ```

Step 2 lead to more transaction check errors :(

At this point I decided to remove Python36:

```
yum remove python36
```

...and install Python3:

```
yum install python3
```

After completing these two steps I have Python 3.6 working again
```
$ python3.6 -V
Python 3.6.8
```

and python3 is installed from RHEL not IUS
```
[root@gw]# yum info python3
Loaded plugins: product-id, rhnplugin, search-disabled-repos, subscription-manager
This system is receiving updates from RHN Classic or Red Hat Satellite.
Installed Packages
Name        : python3
Arch        : x86_64
Version     : 3.6.8
Release     : 10.el7
Size        : 39 k
Repo        : installed
From repo   : rhel-x86_64-server-7
```

EDIT: 

I forgot to mention that step 1 `yum --exclude python3,python3-\* update python36u` ran into an issue:
```
--> Finished Dependency Resolution
Error: Package: python36-devel-3.6.8-2.el7.ius.x86_64 (ius)
           Requires: python3-rpm-macros
```

I resolved this by:
`yum install python3-rpm-macros`

And then try step 1 again

**Comment by carlwgeorge** [comment]
@rsajan

> Step 2 lead to more transaction check errors :(

And those errors are...

> Requires: python3-rpm-macros

Good point, I didn't test with python36u-devel installed at first.  I added a note to my previous comment about that.  Thanks for mentioning it.

> At this point I decided to remove Python36:

Yes, removing then reinstalling is a valid solution as well.

**Comment by yodermk** [comment]
I also had to remove python36u-setuptools and python36u-pip

**Comment by carlwgeorge** [comment]
@yodermk I testing with those installed, and was able to get it to work by adding some escaped wildcards the the commands from https://github.com/iusrepo/packaging/issues/7#issuecomment-545038676.  I modified that comment to include those.

**Comment by cognifloyd** [comment]
Where can I follow the progress towards packing python37/python38 in EPEL?

**Comment by yodermk** [comment]
I wonder that too. I had popped into EPEL IRC a couple months ago and asked, and it sounded like no one was working on it. :(  Carl had noted, though, that Red Hat plans to make an Appstream of 3.8 "shortly after release."  I've not heard that that's happened, but if it does, then maybe EPEL doesn't need it.  Of course that would only apply to EL8, but IMHO if someone needs it badly enough, upgrading from 7 to 8 shouldn't be a huge blocker.

**Comment by cognifloyd** [comment]
I am particularly interested in python37 for CentOS 7 because I have some machines that I cannot update yet, but I need python37 on them. I cringe every time `pyenv` is the best solution I can come up with.

But, I understand that there is (was?) a bunch of cleanup that needed to happen with the python34, python35 and python36 packages before working on python37. @carlwgeorge how is getting python36 from ius merged with epel going? Is there any other cleanup work before attacking python37? Or is there a mailing list or forum that I can read/follow instead of asking about status updates in github?

Has anyone tried building the python37 rpms from fedora in CentOS 7? What would it take to get that into EPEL? Googling, I see https://fedoraproject.org/wiki/Getting_a_Fedora_package_in_EPEL - are there any already-created issues you can point me to in https://src.fedoraproject.org/ about python37 in EPEL for CentOS 7?

**Comment by cognifloyd** [comment]
I don't know if this was the right place, but I filed this request for python37 in EPEL 7: https://bugzilla.redhat.com/show_bug.cgi?id=1781940

**Comment by laidbackpeter** [comment]
I am still facing some issues with this package `python36-mod_wsgi` despite following the instructions. This is the output I am getting `No package matching 'python36-mod_wsgi' found available, installed or updated`.  However `python36u-mod_wsgi` is still available.

Here is the output for `yum repolist`:

```[root@ip-172-31-20-109 ec2-user]# yum repolist 
Loaded plugins: fastestmirror, priorities, s3iam
Loading mirror speeds from cached hostfile
 * base: ftp.heanet.ie
 * epel: mirrors.coreix.net
 * extras: ftp.heanet.ie
 * updates: ftp.heanet.ie
https://repo.ius.io/ius-release-el7.rpm/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
Trying other mirror.
To address this issue please refer to the below wiki article 

https://wiki.centos.org/yum-errors

If above article doesn't help to resolve this issue please use https://bugs.centos.org/.

repo id                                               repo name                                                                    status
base                                                  CentOS 7 - base                                                              10,097
epel                                                  Extra Packages for Enterprise Linux 7 - x86_64                               13,509
extras                                                CentOS 7 - extras                                                               307
ius                                                   IUS YUM repo                                                                    570
kmod-ena                                              AWS ENA kernel module, built by The Scale Factory                                 1
kmod-ixgbevf                                          Intel ixgbevf kernel module, built by The Scale Factory                           2
mysql-connectors-community/x86_64                     MySQL Connectors Community                                                      141
mysql-tools-community/x86_64                          MySQL Tools Community                                                           105
mysql57-community/x86_64                              MySQL 5.7 Community Server                                                      404
puppet-omnibus                                        Scale Factory Puppet omnibus packages                                            40
sclo                                                  Software Collections.org: 7 - sclo                                            8,770
updates                                               CentOS 7 - updates                                                            1,010
yum-s3-iam                                            S3-IAM plugin for yum, built by The Scale Factory                                 3
repolist: 34,959
```

and here is the output for the python I am using:
```[root@ip-172-31-20-109 ec2-user]# yum info python3
Loaded plugins: fastestmirror, priorities, s3iam
Loading mirror speeds from cached hostfile
 * base: ftp.heanet.ie
 * epel: mirrors.coreix.net
 * extras: ftp.heanet.ie
 * updates: ftp.heanet.ie
https://repo.ius.io/ius-release-el7.rpm/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
Trying other mirror.
To address this issue please refer to the below wiki article 

https://wiki.centos.org/yum-errors

If above article doesn't help to resolve this issue please use https://bugs.centos.org/.

Available Packages
Name        : python3
Arch        : i686
Version     : 3.6.8
Release     : 10.el7
Size        : 69 k
Repo        : base
Summary     : Interpreter of the Python programming language
URL         : https://www.python.org/
License     : Python
```

Any idea what I am could missing? cc @carlwgeorge

**Comment by fdintino** [comment]
Based on my reading of [this thread](https://lists.fedoraproject.org/archives/list/epel-devel@lists.fedoraproject.org/thread/V336LVAXNJKVRECQ7XRLKICQIMVBDUAR/) in epel-devel, it doesn't seem that EPEL is going to allow `python37*` packages.

**Comment by carlwgeorge** [comment]
@cognifloyd Thanks for creating that epel7 branch request for python37.  I started a new job, so I haven't had much time to work on the rest of the python cleanup work, much less working on python37 or python38.  Those things aren't really dependent on each other, I just didn't want to take on more python work before I got caught up.  Anyone can get involved with the Fedora Python SIG and keep that process going without my involvement.  I would like to see it happen as well and may eventually be able to handle it myself, but I can't commit to that.  IUS doesn't have a mailing list anymore, all the work happens here on GitHub.  No updates on this issue simply means there hasn't been any change.

@laidbackpeter Someone needs to add python3-mod_wsgi to EPEL, ideally with an obsolete for python36u-mod_wsgi.  Again, this is something I'd like to take care of, but my time is limited and if anyone wants to get that started they don't need to wait on me.

@fdintino I'm not sure how you came to that conclusion.  Nothing has been denied.  Smooge said he would prefer not to do it, but all it takes is volunteers who _are_ willing to do it.  The big part of Smooge's frustration (and others) was the complications around switching the default `/usr/bin/python3` from python34 to python36.  Now that python3 is in the base operating system, that won't happen again.  Any other pythons added at this point will be supplementary and will never replace the stock `/usr/bin/python3`.

**Comment by cognifloyd** [comment]
> I would like to see it happen as well and may eventually be able to handle it myself, but I can't commit to that. IUS doesn't have a mailing list anymore, all the work happens here on GitHub. No updates on this issue simply means there hasn't been any change.

@carlwgeorge thanks for the details. I will remain subscribed for updates. I also can't commit to maintaining a package for any length of time with my current and expected work load. Best of luck on your new job!

**Comment by laidbackpeter** [comment]
Thanks @carlwgeorge

**Comment by cognifloyd** [comment]
Following up: It looks like EPEL 7 will never get python37. So IUS is probably the only path forward for python37 in CentOS 7.
EPEL 8 is likely to get python38 though, so that is promising. Maybe that means EPEL 7 has more of a chance of getting python38.
See: https://bugzilla.redhat.com/show_bug.cgi?id=1781940#c6

**Comment by cognifloyd** [comment]
I'm much more likely to be able to contribute to IUS than to Fedora/EPEL. Submitting PRs on Github works just fine with my toolset. My dev machine is gentoo, so getting all the tooling to be able to work with the Fedora infrastructure is non-trivial, and not worth it for me.

So, what's the next step on cleaning up python on IUS? If someone else can handle any required changes in EPEL then I can help with things here on github.

**Comment by cognifloyd** [comment]
It looks like python35u packages are still available, but I don't see any python35 repos. Does that still need to be transitioned from python35u to python35? Or is it just considered obsolete now, so we can ignore it?
What about python36 - is anything else left to clean that up in IUS? It looks like the packages have already been renamed from python36u to python36.

**Comment by smathema** [comment]
I see an issue with the pip after the change: 

`$python3.6 -m pip list`

`Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib64/python3.6/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib64/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/usr/lib/python3.6/site-packages/pip/__init__.py", line 42, in <module>
    from pip.utils import get_installed_distributions, get_prog
  File "/usr/lib/python3.6/site-packages/pip/utils/__init__.py", line 27, in <module>
    from pip._vendor import pkg_resources
  File "/usr/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3018, in <module>
    @_call_aside
  File "/usr/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3004, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3046, in _initialize_master_working_set
    dist.activate(replace=False)
  File "/usr/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2578, in activate
    declare_namespace(pkg)
  File "/usr/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2152, in declare_namespace
    _handle_ns(packageName, path_item)
  File "/usr/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2092, in _handle_ns
    _rebuild_mod_path(path, packageName, module)
  File "/usr/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2121, in _rebuild_mod_path
    orig_path.sort(key=position_in_sys_path)
AttributeError: '_NamespacePath' object has no attribute 'sort'
`

Steps taken to update from python36u to python36 packages:
`sudo yum remove python3*`

`sudo yum install python3-rpm-macros`

`sudo yum install python36 python36-devel python36-pip --disablerepo=* --enablerepo=ius`

The yum packages that were installed:

`$yum list installed python3*`

`Installed Packages`
`python3-rpm-macros.noarch                                                                 3-32.el7                                                                        @base`
`python36.x86_64                                                                           3.6.8-2.el7.ius                                                                 @ius`
`python36-devel.x86_64                                                                     3.6.8-2.el7.ius                                                                 @ius`
`python36-libs.x86_64                                                                      3.6.8-2.el7.ius                                                                 @ius`
`python36-pip.noarch                                                                       9.0.1-2.el7.ius                                                                 @ius`
`python36-setuptools.noarch                                                                39.2.0-4.el7.ius                                                                @ius`

Running command like `pip3 list` doesn't show me the error mentioned on the beginning of the comment, but using `python3 -m pip list` or `python3.6 -m pip list` does generate error..

Is there any step I'm doing wrong, any help is highly appreciated

**Comment by carlwgeorge** [comment]
@cognifloyd

> It looks like python35u packages are still available, but I don't see any python35 repos.

The python35u package sources are still in the old GitHub organization, e.g. https://github.com/iuscommunity-pkg/python35u.

> Does that still need to be transitioned from python35u to python35?

Yes, as well as being ported to our new [build system](https://github.com/iusrepo/infrastructure/wiki/Build-Process).

> Or is it just considered obsolete now, so we can ignore it?

Technically not obsolete yet, as it's maintained upstream until [2020-09-13](https://devguide.python.org/#status-of-python-branches).  But seeing as it's EOL in less than a month I doubt it will get worked on again before being retired.  I'm open to accepting pull requests for it if someone needs it badly and can't use the stock python3 (3.6) for whatever reason.

> What about python36 - is anything else left to clean that up in IUS? It looks like the packages have already been renamed from python36u to python36.

For EL7, all IUS packages have been renamed to drop the "u" suffix so that RHEL or EPEL packages can obsolete them to transition users.  For EL6, IUS python36 packages are still valid.  If there is anything out of date I'm happy to review pull requests to update it.

**Comment by carlwgeorge** [comment]
@smathema I'm not able to reproduce your error.  Perhaps you installed something with pip that overwrote stock files?  You could [verify the installed files](https://www.mankier.com/8/rpm#Description-Verify_Options) to debug this, but I'm more interested in why you are disabling every repo except for IUS when installing python36.  The idea is that the python3 from RHEL/CentOS obsoletes python36, so that you use the package from the distro and not from a third party repo.  Without disabling any repos, update your system so that stock python3 gets installed and see if that resolves your issue.

**Comment by x-yuri** [comment]
The way I migrated from Python 3.5 to Python 3.6 on CentOS 7:

`/root/_/upgrade-python.sh`:

```sh
set -eux
yum install -y python3 python3-devel \
    https://archives.fedoraproject.org/pub/archive/epel/7.7/x86_64/Packages/u/uwsgi-plugin-python36-2.0.17.1-2.el7.x86_64.rpm \
    https://archives.fedoraproject.org/pub/archive/epel/7.7/x86_64/Packages/u/uwsgi-plugin-common-2.0.17.1-2.el7.x86_64.rpm \
    https://archives.fedoraproject.org/pub/archive/epel/7.7/x86_64/Packages/u/uwsgi-2.0.17.1-2.el7.x86_64.rpm
yum remove -y uwsgi-plugin-python35u
yum install -y uwsgi-plugin-python36
su - NAME -c _/recreate-env.sh
sed -Ei "s/python35u/python36/" /etc/uwsgi.d/NAME.ini
```

`/home/NAME/_/recreate-env.sh`:

```sh
set -eux
cd site
mv env env-`date +%Y%m%d-%H%M%S`
python3 -m venv env
. env/bin/activate
pip install -r current/requirements.txt
```

**Comment by carlwgeorge** [comment]
The IUS project has reached it's end of life, and will not be addressing any more issues or pull requests.

ius.io/faq#why-doesnt-ius-have-packages-for-rhel-8

iusrepo/announce#41
