### ISSUE TITLE
git2u-all disappeared

### ISSUE THREAD

**Issue by nussera** [iusrepo/packaging#8]
Hi,

Since yesterday, 18.May 2020, the package git2u-all can't be found for Centos7 x86_64.
On the 15.May 2020, it was still there.
If it was removed on purpose, what is the best alternative?

I created this issue here, because there are 3 git related git repos and I don't know where it would belong too.

Thanks for your help!

**Comment by carlwgeorge** [comment]
https://github.com/iusrepo/announce/issues/19

I highly recommend subscribing to that repository to get notified of package EOL announcements.
