### ISSUE TITLE
ARM Packages

### ISSUE THREAD

**Issue by ThisIsQasim** [iusrepo/packaging#9]
**What new package do you want?**
Packages targeting Aarch64 architecture

**Why?**
ARM CPUs provide a better performance/$ & performance/watt in certain environments. These CPUs are gaining popularity. It would be helpful if packages for this architecture were readily available.

**Testing**

I agree to test the new package to ensure that it works as expected.  Once I am satisfied with the results of my testing I will comment on this issue with the word "STABLE" to get it promoted to the stable repos.

**Comment by carlwgeorge** [comment]
As [documented in our wiki](https://github.com/iusrepo/infrastructure/wiki/Build-Process), we build our packages in Cirrus CI.  They do not yet support ARM, but it is [being discussed](https://github.com/cirruslabs/cirrus-ci-docs/issues/218).  If they enable ARM support in the community cluster, IUS should in theory be able to start building for that architecture.  There would be some additional work to deliver those packages once built, but hopefully we can do it one day.

**Comment by schlitzered** [comment]
hey, seems like aarch64/arm64 support is now available with cirrus ci. any chance that IUS makes arm packages available now?

**Comment by demonfoo** [comment]
Any progress on this? With the increasing push, and better economics of (for example) AWS' ARM server chips, ARM64 support is becoming more interesting.

**Comment by chrisgilmerproj** [comment]
@carlwgeorge - are there any updates on supporting aarch64/arm64 now that Cirrus CI has got their changes in? And if not is there a way for the community to support adding the support?

**Comment by carlwgeorge** [comment]
It has come to my attention that [RHEL 7 for aarch64 is no longer maintained as of 2020-11-30](https://access.redhat.com/support/policy/updates/errata#Life_Cycle_Dates).  Because of that I don't think it makes sense to enable IUS builds for aarch64.

**Comment by chrisgilmerproj** [comment]
Thanks for the update! I'll look into migrating to a newer version of RHEL.
